version: smartide/v0.2
orchestrator:
  type: docker-compose
  version: 3
workspace:
  dev-container:
    service-name: smartide
    webide-port: 6800
    ide-type: vscode
    volumes:
      git-config: true
      ssh-key: true
  services:
    smartide:
      image: registry.cn-hangzhou.aliyuncs.com/chileeb/smartide-opvscode-php:latest
      restart: always
      environment:
        POSTGRES_HOST_AUTH_METHOD: trust
        ROOT_PASSWORD: root123
      volumes:
        - .:/home/project
      expose:
        - 3000
      ports:
        - 8080:80
      networks:
        - smartide-network
  networks:
    smartide-network:
      external: true