version: "3.8"

services:
  itop-web:
    image: registry.cn-hangzhou.aliyuncs.com/chileeb/itop:1.0
    restart: always
    ports:
      - 8090:80
    networks:
      - itop-network
  itop-db:
    image: registry.cn-hangzhou.aliyuncs.com/chileeb/mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: leansoft
    restart: always
    volumes:
      - .ide/mysql/conf/my.cnf:/etc/my.cnf
      - /tmp/mysql-db:/var/lib/mysql
    ports:
      - 3366:3306
    networks:
      - itop-network
networks:
  itop-network: